# Generated by Django 5.0 on 2024-04-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device_token',
        ),
    ]
