# Generated by Django 5.0 on 2024-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_task_assigned_count',
            field=models.IntegerField(default=0),
        ),
    ]
