# Generated by Django 5.0 on 2024-04-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_task_completed_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='task_completed_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_task_assigned_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
