# Generated by Django 5.0 on 2024-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_task_completed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='completed_tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
