# Generated by Django 5.0 on 2024-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_assigned_tasks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_assigned_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='task_done_counter',
            field=models.IntegerField(default=0),
        ),
    ]
