# Generated by Django 5.0 on 2024-04-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_amountgiven_spend_delete_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='left_money',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
