# Generated by Django 5.0 on 2024-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_spend_left_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountgiven',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
