# Generated by Django 5.0 on 2024-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_alter_amountgiven_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountgiven',
            name='amount_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
