# Generated by Django 5.0 on 2024-04-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
